### ISSUE TITLE
[BUG] Emoji reactions by the user are interpreted as setting the self-destruct timer

### ISSUE THREAD

**Issue by MoemUT** [nanu-c/axolotl#148]
### Description

Emoji reactions are not shown, but instead trigger a message that suggests the user set the timer for self-destructing messages to 0s.

### Steps to Reproduce

1. Join an existing Group
2. Wait until someone sends an emoji reaction
3. See the following incorrect alert appear:
_[user] set timer for self-
destructing messages 
0s_

**Expected behavior:** Emoji reactions should be displayed as emojis on the message that the user reacted to. Or they should be ignored until Axolotl can display them.

**Actual behavior:** An alert about setting the timer for self-destructing messages to 0s is displayed.

#### Versions

Axolotl Beta 0.8.2

#### Device

Oneplus One (Bacon) running Ubuntu Touch

#### Link to Debug Log
Sorry, no idea how or where to get this.

**Comment by nanu-c** [comment]
Solved in 0.8.7

**Comment by Flaburgan** [comment]
This is solved as the message about timer isn't displayed anymore, but the reactions are not there yet, right?

**Comment by MoemUT** [comment]
I can see the reactions, so that's very good improvement. The faulty message is indeed gone.
I cannot see who posted them, or as a reaction on which message.

**Comment by MoemUT** [comment]
Screenshot is here: [https://i.imgur.com/cgeI1hf.png](https://i.imgur.com/cgeI1hf.png)

**Comment by Flaburgan** [comment]
Reactions by the contacts are now displayed (but as a separate message, but we'll have another issue for this) but reactions by the user still create this "Timer" message. So this issue is still valid.

**Comment by MoemUT** [comment]
This is the current state of reactions in my installation:
"I can see the reactions, so that's very good improvement. The faulty message is indeed gone.
I cannot see who posted them, or as a reaction on which message."

Running Axolotl 1.0.8 on Ubuntu Touch on Sony Xperia X.
