### ISSUE TITLE
[Feature] Update Icon

### ISSUE THREAD

**Issue by mikeshenson** [nanu-c/axolotl#841]
**Is your feature request related to a problem? Please describe.**
No problem! Great app! I have been using the app for 8+ months.

**Describe the solution you'd like**
I want to see a cleaner Icon on my PinePhone running Arch Linux Arm.

**Describe alternatives you've considered**
I attached the svg I created. The random message is to indicate encrypted texting.

**Additional context**
![axolotl_screenshot](https://user-images.githubusercontent.com/7337270/175423730-e64bee99-6c5f-4b9d-9416-858d1c6720db.png)
![axolotl](https://user-images.githubusercontent.com/7337270/175423734-2d0960c6-e79b-45da-ba2e-580997369d59.svg)

**Comment by olof-nord** [comment]
I am far from a designer, this would primarily be a question for @nanu-c. Some initial idea would be what, if any, to put in the speech bubble. Comparing it to the Signal icon, which has a speech bubble but no text, I think I would prefer a clean white background.

**Comment by mikeshenson** [comment]
Done, see attached.

![axolotl](https://user-images.githubusercontent.com/7337270/179420010-e2cccc96-ae53-4f17-83a8-73c96ae3f278.svg)
.

**Comment by nanu-c** [comment]
Actually this icon fits nicely into the mobian environment, whereby it should also fit into ubuntu touch eco system. There we have a more "clean" paradigm and a folding paper background guideline. This is why have a background in the current logo. You can see examples for them here: https://open-store.io/  . And it has to work with the website https://axolotl.chat/ 
I'm still not convinced to change it ;)
